import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import '../style/font.css'
import "../style/ui.css";
import "../style/sitelayout.css";
import "../style/globals.css";
import { Toaster } from "react-hot-toast";
import Master from "@/utils/MasterHelper";
// import "bootstrap/dist/js/bootstrap.bundle.min.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const popins = Poppins({
  variable: "--font-popins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Maia Care Doctor Inhouse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${popins.variable}`}>
        
        <Master>
          {children}
        </Master>
         <Toaster
        position="top-right"
        toastOptions={{
          success: {
            style: {
              background: '#2ECF98',
              color: '#fff',
            },
          },
          error: {
            style: {
              background: 'red',
              color: '#fff',
            },
          },
        }}
      />
      </body>
    </html>
  );
}
